---
namespace: k3s
name: orchestration
version: 1.0.0

readme: README.md
authors:
  - PHAM Daniel <phamdaniel64000@gmail.com>

description: Build a Kubernetes cluster using K3s via Ansible

license:
  - MIT

tags: ['infrastructure', 'linux', 'tools']

dependencies:
  community.general: ">=7.0.0"
  ansible.posix: ">=1.5.0"

repository: https://github.com/shinlchi/k3s-ansible

